app_name:		"YourAppName" 			# TODO: test/support names w/ spaces yet
namespace:		"com.your.namespace" 	# Java-like naming here, as the app wrapper IS Java
app_dir: 		"/path/to/app" 			# Next directory down should be enyo "bootplate" dir
phonegap_dir: 	"/path/to/phonegap" 	# Downloaded from http://phonegap.com/download/ & unpacked